# Generated by Django 3.0.14 on 2022-01-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermember', '0012_auto_20220102_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='std_img',
            field=models.ImageField(default='user/image-student/hinh-anh-gai-xinh-de-thuong-nhat-1.jpg', upload_to='user/image-student/'),
        ),
    ]
